blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap
from pygems.sitemaps import PostSitemap

sitemaps = {
    'posts':PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pygems/',include('pygems.urls',namespace='pygems'),),
    path('tinymce/',include('tinymce.urls'),),

    path('sitemap.xml',sitemap,{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap')
    ]

pygems/urls.py
from django.urls import path
from . import views

app_name = 'pygems'

urlpatterns = [
#post view
path('',views.post_list,name='post_list'),
path('tag/<slug:tag_slug>/',views.post_list,name='post_list_by_tag'),
path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_details,name='post_details'),
path('<int:post_id>/share/',views.post_share,name='post_share')
]

pygems/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import	TaggableManager
from tinymce import models as tmodels

# Create your models here.

class PublishedManager(models.Manager):
	def get_queryset(self):
		return super(PublishedManager,self).get_queryset().filter(status="Published")


class Post(models.Model):
	""" Post Model"""
	# custom manager
	objects = models.Manager()
	published = PublishedManager()


	STATUS_CHOICES = (('draft','Draft'),('published','Published'))
	title = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250,unique_for_date='publish')
	author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
	body = tmodels.HTMLField(max_length=2000)
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')

	tags = TaggableManager()

	def get_absolute_url(self):
		return reverse('pygems:post_details',args=[self.publish.year,self.publish.month,self.publish.day,self.slug])

	class Meta:
		ordering = ('-publish',)
		
	def __str__(self):
		return self.title 


class Comment(models.Model):
	post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = tmodels.HTMLField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ('created',)
	def __str__(self):
		return f'comment by {self.name} on {self.post}'

pygems/forms.py
from django import forms
from django.db import models
from .models import Comment 


class EmailPostForm(forms.Form):
	name = forms.CharField(max_length=25)
	# email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['name','email','body']

pygems/views.py
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

from .models import Post,Comment
from taggit.models import Tag

from .forms import EmailPostForm,CommentForm
from django.core.mail import send_mail

from django.db.models import Count
# Create your views here.

def  post_list(request,tag_slug=None):
	object_list = Post.objects.all()
	tag = None
	if tag_slug:
		tag = get_object_or_404(Tag,slug=tag_slug)
		object_list = object_list.filter(tags__in=[tag])
	paginator = Paginator(object_list,3)

	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)
	return render(request,"pygems/list.html",{'page':page,'posts':posts,'tag':tag})


def post_details(request,year,month,day,post):
	post = get_object_or_404(Post,slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)
	comments = post.comments.filter(active=True)
	post_tags_ids = post.tags.values_list('id',flat=True)
	print(list(post_tags_ids))
	similar_posts = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
	print(similar_posts)
	similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
	print(similar_posts)
	new_comment = None
	if request.method == 'POST':
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			new_comment = comment_form.save(commit=False)
			new_comment.post = post
			new_comment.save()
		
	else:
		comment_form = CommentForm()
	return render(request,"pygems/details.html",{'post':post,'comments':comments,
		'new_comment':new_comment,'comment_form':comment_form,'similar_posts':similar_posts})


def post_share(request,post_id):
	post = get_object_or_404(Post, id = post_id, status="published")
	sent = False
	if request.method == 'POST':
		form = EmailPostForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			post_url = request.build_absolute_uri(post.get_absolute_url())
			subject = f"{cd['name']} recomended to read { post.title }"
			message = f"Read {post.title} at {post_url}\n\n {cd['name']} \'s comments : {cd['comments']}"
			send_mail(subject,message,'ruba.bd2019@gmail.com',[cd['to']])
			sent = True
	else:
		form = EmailPostForm()
	return render(request,"pygems/share.html",{'post':post,'form':form,'sent':sent })
	

pygems/templates/pygems/base.html
{% load pygems_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="{% static "css/style.css" %}">
	<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<style type="text/css">


</style>
</head>
<body >
	<div id="content">
		{% block content %}

		{% endblock %}
	</div>
<!-- 	<div id="sidebar">
		<h2>from base page</h2>
		<p>This is My blog I'have written {% total_posts %} posts so far</p>
	</div> -->
</body>
</html>

pygems/templates/pygems/details.html
{% extends "pygems/base.html" %}
{% block title %} {{post.title}} {% endblock %}

{% block content %}
{% include "pygems/navigation.html" %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-lg-8 col-xl-12">
<h1>{{post.title}}</h1>
<p class="date">
	published {{ post.publish }} by {{ post.author }}
</p>

{{ post.body | linebreaks }}

<p>
	<a href="{% url "pygems:post_share" post.id %}">
		Share the Post 
	</a>
</p>


<h2>Similar post</h2>
{% for post in similar_posts %}
<p><a href="{{post.get_absolute_url}}">{{post.title}}</a></p>
{% empty %}
There is no similar Post yet
{% endfor %}

{% with comments.count as total_comments %}
<h2>{{total_comments}} comment {{total_comments|pluralize }}</h2>
{% endwith %}

{% for comment in comments %}
<div class="comment">
	<p class="info">
		Comment {{forloop.counter }} by {{comment.name}}
		{{comment.created}}
	</p>
	{{comment.body|linebreaks}}
</div>
{% empty %}
<p>There is no comment yet</p>
{% endfor %}

{% if new_comment %}
<h2>Your comment has ben added</h2>
{% else %}
<h2>Add a new comment </h2>
<form method="post">
	{{comment_form.as_p}}
	{% csrf_token %}
	<p><input type="submit" value="Add commet" ></p>
</form>

{% endif %}

       </div>
        </div>
    </div>


{% endblock %}

pygems/templates/pygems/list.html
{% extends "pygems/base.html" %}
{% block title %} My Blog {% endblock %}

{% block content %}

{% include "pygems/navigation.html" %}


<!-- {% if tag%}
<h2>Posts tagged with "{{tag.name}}"</h2>
{% endif %} -->

{% for post in posts %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-lg-8 col-xl-12">
                <div class="post-preview"><a href="{{ post.get_absolute_url }}">
                        <h2 class="post-title">{{ post.title }}</h2>
                    </a>
                    <p style="height: 30px;width: 767px;">Tags : {% for tag in post.tags.all %}
						<a href="{% url 'pygems:post_list_by_tag' tag.slug %}"> {{tag.name}}</a>
						{% if not forloop.last %},{% endif %}
						{% endfor %}</p>
                    <p class="post-meta">published {{ post.publish }} by {{ post.author }}</a></p>
                </div>
                <hr>
              
                
                <div class="clearfix"></div>

                {{ post.body | truncatewords:300 | linebreaks }}<hr>

            </div>
        </div>
    </div>


{% endfor %}

{% include "pygems/pagination.html" with page=posts %}

{% endblock%}

pygems/templates/pygems/navigation.html
{% load static %}
<div style="padding-bottom: 10px;text-align: center;border-bottom-style: solid;border-bottom-color: rgb(98,158,218);">
<h1 class="text-center bounce animated" style="font-size: 50px;font-family: Aclonica, sans-serif;color: var(--bs-cyan);">PyGems</h1>
</div>

pygems/templates/pygems/pagination.html
<div class="container">
<div class="row">
<div class="col-md-10 col-lg-8 col-xl-12">
<div class="pagination">
	<span class="step-links">
		{% if page.has_previous %}
		<a href="?page={{page.previous_page_number }}"> Previous </a>
		{% endif %}

	<span class="current">
		Page {{page.number}} of {{page.paginator.num_pages}}
	</span>
	{% if page.has_next %}
	<a href="?page={{page.next_page_number }}"> Next </a>
	{% endif%}

	</span>
</div>
</div>
</div>
</div>

pygems/templates/pygems/share.html
{% extends "pygems/base.html" %}

{% block title %} Share a post {% endblock %}


{% block content %}
{% include "pygems/navigation.html" %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-lg-8 col-xl-12">

{% if sent %}
<h1>Email successfully sent to {{ form.cleaned_data.to }}. </h1>
<p> "{{post.title}}" was sucessfully sent to {{ form.cleaned_data.to }} </p>

{% else %}

<h1>Share "{{post.title}}" by email </h1>

<form method="post">
	{{form.as_p}}
	{% csrf_token %}
	<input type="submit" value="Send email">
</form>
{% endif %}

      </div>
        </div>
    </div>


{% endblock %}